module.exports = {
  projects: [
    '<rootDir>/apps/webapp',
    '<rootDir>/libs/zoneaware/rx-for',
    '<rootDir>/libs/auth/firebase',
    '<rootDir>/libs/auth/ui',
    '<rootDir>/libs/ui/webapp/template',
    '<rootDir>/libs/account',
    '<rootDir>/libs/storage/firebase',
    '<rootDir>/libs/storage/core',
    '<rootDir>/libs/dashboard',
    '<rootDir>/libs/pref-utils/rx-effects',
    '<rootDir>/libs/pref-utils/cdk',
    '<rootDir>/libs/boinc',
    '<rootDir>/libs/ms-to-time',
    '<rootDir>/apps/backend/opishub',
    '<rootDir>/libs/passport/firebase',
    '<rootDir>/apps/marketing/frontend',
    '<rootDir>/libs/hooks/use-memo-compare',
    '<rootDir>/libs/hooks/use-media',
    '<rootDir>/libs/hooks/use-dark-mode',
    '<rootDir>/libs/hooks/use-firestore-query',
    '<rootDir>/libs/hooks/use-debounce',
    '<rootDir>/libs/marketing/ui',
  ],
};
